import { pgTable, serial, text, numeric, boolean, timestamp, date, pgEnum } from "drizzle-orm/pg-core";

export const employeeStatusEnum = pgEnum("employee_status", ["active", "retired", "resigned", "terminated", "on_leave"]);
export const employeeCategoryEnum = pgEnum("employee_category", ["regular", "contract", "daily_wage", "deputation"]);
export const employeeTypeEnum = pgEnum("employee_type", ["officer", "other"]);

export const employees = pgTable("employees", {
  id:               serial("id").primaryKey(),
  empCode:          text("emp_code").notNull().unique(),
  name:             text("name").notNull(),
  fatherName:       text("father_name"),
  designation:      text("designation").notNull(),
  department:       text("department").notNull(),
  category:         employeeCategoryEnum("category").notNull().default("regular"),
  maritalStatus:    text("marital_status").default("Unmarried"),
  aadharCard:       text("aadhar_card"),
  lastQualification:text("last_qualification"),
  sex:              text("sex").default("M"),
  dob:              date("dob"),
  doa:              date("doa"),
  joinDate:         date("join_date"),
  retirementDate:   date("retirement_date"),
  empGroup:         text("emp_group"),
  paybillGroup:     text("paybill_group"),
  payLevel:         text("pay_level"),
  contributionType: text("contribution_type").default("GPF"),
  incrMonth:        text("incr_month"),
  incrPercent:      text("incr_percent"),
  gisLicNo:         text("gis_lic_no"),
  phone:            text("phone"),
  centralized:      boolean("centralized").default(false),
  email:            text("email"),
  address:          text("address"),
  panNo:            text("pan_no"),
  gpfNo:            text("gpf_no"),
  basicPay:         numeric("basic_pay", { precision: 12, scale: 2 }),
  grade:            text("grade"),
  bankAccount:      text("bank_account"),
  branchSolId:      text("branch_sol_id"),
  bankName:         text("bank_name"),
  ifsc:             text("ifsc"),
  pfAccount:        text("pf_account"),
  cpfAccount:       text("cpf_account"),
  cboRegNo:         text("cbo_reg_no"),
  pran:             text("pran"),
  isNpsDeduction:   boolean("is_nps_deduction").default(false),
  photoUrl:         text("photo_url"),
  signatureUrl:     text("signature_url"),
  isSuspended:      boolean("is_suspended").default(false),
  isRetired:        boolean("is_retired").default(false),
  isDisabled:       boolean("is_disabled").default(false),
  isTransferred:    boolean("is_transferred").default(false),
  isPensionable:    boolean("is_pensionable").default(false),
  employeeType:     employeeTypeEnum("employee_type").notNull().default("other"),
  status:           employeeStatusEnum("status").notNull().default("active"),
  isActive:         boolean("is_active").notNull().default(true),
  createdAt:        timestamp("created_at").notNull().defaultNow(),
  updatedAt:        timestamp("updated_at").notNull().defaultNow(),
});
